### ISSUE TITLE
关于yes or no训练的问题

### ISSUE THREAD

**Issue by xilinniao123** [circlePi/2019Cail-A-Bert-Joint-Baseline-for-Machine-Comprehension#1]
感谢分享：
想请教下关于 yes or no训练样本的过程！
关于example转换为features的过程在文件 data_processor.py 函数 ，
对于yes or no的 段落，
只有第一个doc span会形成真正的 训练数据（feature类型为yes 或者 no），其他的span都是当作是 out of span会被当作 noanswer看待！－－－－但是真实的案例中 yes or no的证据不一定出现在开头而是有可能出现在中间，这样做是否不太合理

**Comment by circlePi** [comment]
是的，这里其实可以通过计算 问题-Span相似度，取出yes no最佳段落
